application:
  name: "my_app"
  server:
    host: "${SERVER_HOST:0.0.0.0}"
    port: ${SERVER_PORT:8080}
  config:
    profiles: ${APPLICATION_PROFILES:dev}
    sources:
    - path: "app-${APP_VERSION:v1}.yml"
    - dir: "/opt/app/config"
    - git: "https://github.com/abhishekghoshh/config-client"
      dir: "/sample-config"
      branch: "main"
    - link: https://raw.githubusercontent.com/abhishekghoshh/config-client/refs/heads/master/sample-config/app-1.yaml